// AUTO-GENERATED by budget-build.js — aggregates only, encrypted.
const BUDGET_ENC = {"v":1,"kdf":"PBKDF2-SHA256","iter":310000,"salt":"0+rMKQukYbKx5iPTvdUkDQ==","iv":"nBtXbp0WR9q/e/dn","ct":"iqikwFfmaI9BlX1v2ru9SVQlZUI40Z2cKcKBrvdpq+nw5sV6xVROT+fmA85He3rAeKvvs0r6U9H3Gh33lV+z6zwjs44D"};
