// AUTO-GENERATED by build.js — do not edit directly.
// Edit/add recipes under recipes/sources/<Person>/<recipe-id>.json, then run: node build.js
const RECIPES = [
  {
    "id": "light-vegetable-stock-soup-soya-croutons",
    "title": "Light Vegetable Stock Soup with Crispy Soya Croutons",
    "category": "Soup",
    "dateAdded": "2026-07-20",
    "tags": [
      "soup",
      "light",
      "protein-rich",
      "vegetarian"
    ],
    "note": "A light, healthy, protein-rich soup with a clear homemade vegetable stock.",
    "nutrition": {
      "servings": 2,
      "perServing": {
        "calories": 165,
        "protein_g": 12,
        "carbs_g": 9,
        "fat_g": 9,
        "fiber_g": 4
      },
      "estimated": true,
      "note": "LLM estimate from ingredient quantities"
    },
    "ingredientGroups": [
      {
        "heading": "For the vegetable stock",
        "items": [
          "½ bunch fresh parsley",
          "Stems from 1 bunch of coriander (use only the lower stem portion)",
          "½ radish, roughly chopped",
          "¾ cup radish leaves, chopped",
          "3–4 cups water"
        ]
      },
      {
        "heading": "For the soup",
        "items": [
          "Soya croutons (or soya chunks/crisps)",
          "A few drops of oil",
          "2–3 tablespoons peanuts",
          "¼–½ cup bean sprouts",
          "2–3 baby corn, sliced",
          "Chili flakes, to taste",
          "1–2 Thai red chilies, finely chopped and soaked in white vinegar",
          "Salt, to taste",
          "Fresh lime wedges"
        ]
      }
    ],
    "methodGroups": [
      {
        "heading": "Prepare the vegetable stock",
        "steps": [
          "Add the parsley, coriander stems, radish, and radish leaves to a pot.",
          "Pour in 3–4 cups of water.",
          "Bring to a boil, then simmer for 30–40 minutes.",
          "Strain the vegetables and keep the clear stock aside."
        ]
      },
      {
        "heading": "Prepare the toppings",
        "steps": [
          "Heat a pan with just a few drops of oil. Sauté the soya croutons until they become lightly browned and crispy. Remove and set aside.",
          "In the same pan, dry roast the peanuts until they develop light reddish-brown spots. Cool them slightly, rub off the skins, and grind into a coarse powder."
        ]
      },
      {
        "heading": "Make the soup",
        "steps": [
          "Pour about 1½ cups of the prepared vegetable stock into a saucepan and bring it to a boil.",
          "Add the crispy soya croutons, bean sprouts, sliced baby corn, chili flakes, salt, and the chopped Thai chilies with a little of the vinegar.",
          "Simmer for 1–2 minutes, just until the vegetables are slightly tender but still crisp."
        ]
      },
      {
        "heading": "Serve",
        "steps": [
          "Pour the soup into a serving bowl. Sprinkle the roasted peanut powder generously on top and finish with a squeeze of fresh lime juice.",
          "Serve hot and enjoy a light, healthy, protein-rich soup."
        ]
      }
    ],
    "source": "Mom"
  }
];
