// AUTO-GENERATED by build.js — do not edit directly.
// Edit/add recipes under recipes/sources/<Person>/<recipe-id>.json, then run: node build.js
const RECIPES = [
  {
    "id": "healthy-butter-chicken",
    "title": "Healthy Butter Chicken (High-Protein)",
    "category": "Curry",
    "dateAdded": "2026-07-25",
    "tags": [
      "chicken",
      "curry",
      "high-protein",
      "indian",
      "meal-prep"
    ],
    "note": "A lighter, macro-friendly spin on classic butter chicken — Greek yogurt stands in for heavy cream, keeping the same rich, comforting flavor for a fraction of the calories.",
    "sourceUrl": "https://amateurprochef.com/2026/05/10/healthy-butter-chicken-2/",
    "nutrition": {
      "servings": 4,
      "perServing": {
        "calories": 420,
        "protein_g": 52,
        "carbs_g": 10,
        "fat_g": 15
      },
      "estimated": false,
      "note": "As stated by the recipe creator"
    },
    "ingredientGroups": [
      {
        "heading": "Chicken marinade",
        "items": [
          "800g chicken breast",
          "¾ cup 0% Greek yogurt",
          "1 tbsp lemon juice",
          "1 tbsp ginger garlic paste"
        ]
      },
      {
        "heading": "Marinade spices",
        "items": [
          "2 tsp Kashmiri chili powder",
          "½ tsp turmeric",
          "1 tsp garam masala",
          "1 tsp cumin powder",
          "1 tsp coriander powder",
          "1 tsp salt"
        ]
      },
      {
        "heading": "Curry sauce",
        "items": [
          "1 can (398 mL) fine diced tomatoes",
          "1 medium onion, finely diced",
          "1 tbsp ginger garlic paste",
          "1 tbsp butter",
          "2 tsp oil",
          "½ cup water, to thin the sauce"
        ]
      },
      {
        "heading": "Sauce spices",
        "items": [
          "1½ tsp Kashmiri chili powder",
          "1 tsp coriander powder",
          "1 tsp garam masala",
          "1 tbsp kasoori methi (dried fenugreek leaves)",
          "Salt, to taste"
        ]
      },
      {
        "heading": "Creamy finish",
        "items": [
          "1 cup 0% Greek yogurt",
          "½ tsp honey or sugar (optional)"
        ]
      }
    ],
    "methodGroups": [
      {
        "heading": "Marinate the chicken",
        "steps": [
          "Combine the chicken, yogurt, lemon juice, ginger garlic paste, and all marinade spices in a bowl. Mix well and let sit at least 30 minutes."
        ]
      },
      {
        "heading": "Cook the chicken",
        "steps": [
          "Cook the marinated chicken in a pan or air fryer at 380°F (193°C) for 12–14 minutes, until lightly charred and cooked through. Set aside."
        ]
      },
      {
        "heading": "Build the curry base",
        "steps": [
          "Melt the butter with the oil in a large pan over medium heat. Add the onion and cook until soft and golden, splashing in a little water if it starts to stick.",
          "Stir in the ginger garlic paste for about a minute, then add the tomatoes. Simmer 8–10 minutes until slightly thickened.",
          "Stir in the sauce spices and cook 1–2 minutes more."
        ]
      },
      {
        "heading": "Blend and thin",
        "steps": [
          "Blend the sauce until completely smooth, return it to the pan, and stir in the ½ cup of water to loosen the gravy."
        ]
      },
      {
        "heading": "Finish creamy and serve",
        "steps": [
          "Take the pan off high heat, then stir in the Greek yogurt gradually so the sauce stays smooth rather than splitting.",
          "Add the chicken back in, stir in the garam masala and crushed kasoori methi, and simmer 3–5 minutes before serving."
        ]
      }
    ],
    "source": "AmateurProChef"
  },
  {
    "id": "sheet-pan-chicken-kebabs",
    "title": "Sheet Pan Chicken Kebabs",
    "category": "Kebab",
    "dateAdded": "2026-07-25",
    "tags": [
      "chicken",
      "kebab",
      "mediterranean",
      "sheet-pan",
      "weeknight"
    ],
    "note": "Spiced ground chicken kebabs baked flat on a sheet pan — no grill or skewers needed — served with a bright arugula salad and herb tahini sauce.",
    "sourceUrl": "https://lolajayyum.com/sheet-pan-chicken-kebabs-in-the-oven/",
    "nutrition": {
      "servings": 6,
      "perServing": {
        "calories": 324
      },
      "estimated": true,
      "note": "As estimated by the recipe creator"
    },
    "ingredientGroups": [
      {
        "heading": "Chicken kebab base",
        "items": [
          "2 lb ground chicken, patted dry (or 1.5 lb boneless skinless chicken thighs + 0.5 lb chicken breast if grinding your own)",
          "½ cup parsley, loosely packed",
          "¼ cup dill",
          "½ cup cilantro, loosely packed",
          "1 red bell pepper",
          "3 garlic cloves",
          "1 medium white onion",
          "1½ tsp salt",
          "1 tsp black pepper",
          "½ tbsp cumin",
          "2 tsp smoked paprika",
          "1 tsp turmeric",
          "1 tsp garlic powder",
          "1 tbsp extra virgin olive oil"
        ]
      },
      {
        "heading": "Salad topping",
        "items": [
          "½ white or red onion, thinly sliced",
          "3 cups arugula",
          "1 tsp sumac",
          "⅓ cup chopped parsley",
          "8 oz cherry tomatoes, halved",
          "1½ tsp olive oil",
          "1 tbsp reserved water from the veggies",
          "Salt and pepper, to taste"
        ]
      },
      {
        "heading": "Herb tahini sauce",
        "items": [
          "⅓ cup tahini",
          "Juice of 1½ lemons",
          "½ tsp garlic powder",
          "1 garlic clove, grated",
          "1 tbsp chopped cilantro",
          "1 tbsp chopped dill",
          "2 tbsp Greek yogurt",
          "3 tbsp reserved veggie water"
        ]
      }
    ],
    "methodGroups": [
      {
        "heading": "Prep",
        "steps": [
          "Preheat the oven to 400°F and line a sheet pan with parchment paper."
        ]
      },
      {
        "heading": "Process the aromatics",
        "steps": [
          "Pulse the onion, bell pepper, garlic, parsley, cilantro, dill, and olive oil in a food processor until finely chopped.",
          "Transfer to cheesecloth and squeeze out as much liquid as you can — save that liquid, it flavors both the salad and the sauce later."
        ]
      },
      {
        "heading": "Mix the chicken",
        "steps": [
          "If grinding your own meat, cut the chicken into chunks and run it through a meat grinder first.",
          "Combine the ground chicken with the squeezed vegetables, all the spices, and the remaining olive oil. Mix well by hand until evenly combined."
        ]
      },
      {
        "heading": "Shape and bake",
        "steps": [
          "Spread the chicken mixture about 1 inch thick across the sheet pan, then score it into kebab strips (shape further by hand if needed).",
          "Bake for 18 minutes, then broil on high for 3–5 minutes until the internal temperature reaches 165°F."
        ]
      },
      {
        "heading": "Make the salad",
        "steps": [
          "While the chicken bakes, toss together the sliced onion, arugula, halved cherry tomatoes, parsley, sumac, olive oil, a splash of the reserved veggie water, and salt and pepper to taste."
        ]
      },
      {
        "heading": "Make the tahini sauce",
        "steps": [
          "Whisk the tahini with the lemon juice, grated garlic, garlic powder, cilantro, dill, Greek yogurt, and reserved veggie water.",
          "Thin with a little cold water, a teaspoon at a time, until it reaches the consistency you want."
        ]
      },
      {
        "heading": "Serve",
        "steps": [
          "Brush the kebabs with any remaining veggie water for shine and extra flavor.",
          "Serve wrapped in pita or lavash with the salad and tahini sauce, or as a low-carb bowl with extra vegetables."
        ]
      }
    ],
    "source": "LolaJayyum"
  },
  {
    "id": "light-vegetable-stock-soup-soya-croutons",
    "title": "Light Vegetable Stock Soup with Crispy Soya Croutons",
    "category": "Soup",
    "dateAdded": "2026-07-20",
    "tags": [
      "soup",
      "light",
      "protein-rich",
      "vegetarian"
    ],
    "note": "A light, healthy, protein-rich soup with a clear homemade vegetable stock.",
    "nutrition": {
      "servings": 2,
      "perServing": {
        "calories": 165,
        "protein_g": 12,
        "carbs_g": 9,
        "fat_g": 9,
        "fiber_g": 4
      },
      "estimated": true,
      "note": "LLM estimate from ingredient quantities"
    },
    "ingredientGroups": [
      {
        "heading": "For the vegetable stock",
        "items": [
          "½ bunch fresh parsley",
          "Stems from 1 bunch of coriander (use only the lower stem portion)",
          "½ radish, roughly chopped",
          "¾ cup radish leaves, chopped",
          "3–4 cups water"
        ]
      },
      {
        "heading": "For the soup",
        "items": [
          "Soya croutons (or soya chunks/crisps)",
          "A few drops of oil",
          "2–3 tablespoons peanuts",
          "¼–½ cup bean sprouts",
          "2–3 baby corn, sliced",
          "Chili flakes, to taste",
          "1–2 Thai red chilies, finely chopped and soaked in white vinegar",
          "Salt, to taste",
          "Fresh lime wedges"
        ]
      }
    ],
    "methodGroups": [
      {
        "heading": "Prepare the vegetable stock",
        "steps": [
          "Add the parsley, coriander stems, radish, and radish leaves to a pot.",
          "Pour in 3–4 cups of water.",
          "Bring to a boil, then simmer for 30–40 minutes.",
          "Strain the vegetables and keep the clear stock aside."
        ]
      },
      {
        "heading": "Prepare the toppings",
        "steps": [
          "Heat a pan with just a few drops of oil. Sauté the soya croutons until they become lightly browned and crispy. Remove and set aside.",
          "In the same pan, dry roast the peanuts until they develop light reddish-brown spots. Cool them slightly, rub off the skins, and grind into a coarse powder."
        ]
      },
      {
        "heading": "Make the soup",
        "steps": [
          "Pour about 1½ cups of the prepared vegetable stock into a saucepan and bring it to a boil.",
          "Add the crispy soya croutons, bean sprouts, sliced baby corn, chili flakes, salt, and the chopped Thai chilies with a little of the vinegar.",
          "Simmer for 1–2 minutes, just until the vegetables are slightly tender but still crisp."
        ]
      },
      {
        "heading": "Serve",
        "steps": [
          "Pour the soup into a serving bowl. Sprinkle the roasted peanut powder generously on top and finish with a squeeze of fresh lime juice.",
          "Serve hot and enjoy a light, healthy, protein-rich soup."
        ]
      }
    ],
    "source": "Mom"
  }
];
