// AUTO-GENERATED by todos-build.js from memory/todos.md — do not edit.
const TODOS = {
  "generatedAt": "2026-07-21",
  "inbox": [
    {
      "text": "Do the dishes",
      "added": "2026-07-20"
    },
    {
      "text": "Clean room",
      "added": "2026-07-20"
    },
    {
      "text": "Verify all open loops at work were closed",
      "added": "2026-07-20"
    },
    {
      "text": "Buy a controller",
      "added": "2026-07-20"
    },
    {
      "text": "Plan dinner for tomorrow",
      "added": "2026-07-20"
    },
    {
      "text": "Send dad a demo plan",
      "added": "2026-07-20"
    },
    {
      "text": "Sift through last 20 days of iMessage texts and resolve them",
      "added": "2026-07-20"
    },
    {
      "text": "Fill the trash bag",
      "added": "2026-07-20"
    },
    {
      "text": "Complete dad's Apple call for dev access",
      "added": "2026-07-20"
    }
  ],
  "inProgress": [],
  "done": []
};
